### PR TITLE
Onboarding.js

### PR DESCRIPTION
**Pull request by fallengravity**
This PR adds onboarding.js as a dependency, it allows us to support a wider array of wallets (The list is below), it also handles chainId/networkId checks, along with a wide variety of other features that can be found in their docs.

```
const wallets = [
  {
    walletName: 'coinbase',
  },
  {
    walletName: 'trust',
  },
  {
    walletName: 'metamask',
  },
  {
    walletName: 'authereum',
  },
  {
    walletName: 'trezor',
  },
  {
    walletName: 'ledger',
  },
  {
    walletName: 'lattice',
  },
  {
    walletName: 'fortmatic',
  },
  {
    walletName: 'portis',
  },
  {
    walletName: 'walletConnect',
  },
  {
    walletName: 'opera',
  },
  {
    walletName: 'operaTouch',
  },
  {
    walletName: 'torus',
  },
  {
    walletName: 'status',
  },
  {
    walletName: 'walletLink',
  },
  {
    walletName: 'imToken',
  },
  {
    walletName: 'meetone',
  },
  {
    walletName: 'mykey',
  },
  {
    walletName: 'huobiwallet',
  },
  {
    walletName: 'hyperpay',
  },
  {
    walletName: 'wallet.io',
  },
  {
    walletName: 'atoken',
  },
];
```

### CODE REVIEW

**Comment by fallengravity** [comment]
@hooftly I have done as much testing as I can on this, you will need to complete a full functionality test, let me know if you want to migrate to Ropsten as there is some stuff to be changed.

**Comment by hooftly** [comment]
> @hooftly I have done as much testing as I can on this, you will need to complete a full functionality test, let me know if you want to migrate to Ropsten as there is some stuff to be changed.

This is an awesome addition thank you! Could you please migrate to ropsten?

**Comment by fallengravity** [comment]
There is a bug when adding stakes please see #8, will be addressed once tests are done.

**Comment by hooftly** [comment]
Testing complete.

**Comment by fallengravity** [comment]
This should now be ready to release, I consider this to be the Version 2.0.0 release since there have been major changes, it should also be slightly more optimized due to removals of unused data and code. If you want to change the version number it's in src/layouts/MainLayout.vue

**Review by hooftly — APPROVED** [review]
Well Done

**Pull request merged**
